name: Build and save my Docker image to a registry
on:
  push:
    branches:
      - main # Déclenchement lorsque le code est poussé sur main

env:
  REG_NAME: "exo.container-registry.com" # Nom du registre
  IMAGE_NAME: "backend-app" # Nom de votre image dans le registre

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker login
        run: |
          docker login -u quentin.badoud@edufr.ch -p ${{ secrets.PWDREGISTRY }} $REG_NAME
          docker build -f src/backend/Dockerfile -t $REG_NAME/$REPOSITORY:latest .
          docker push $REG_NAME/$REPOSITORY:latest
